

#define GROUP1_DATA_PIN 2
#define GROUP1_CLOCK_PIN 3
#define GROUP1_CHIP_SELECT_PIN 4

#define GROUP2_DATA_PIN 5
#define GROUP2_CLOCK_PIN 6
#define GROUP2_CHIP_SELECT_PIN 7

#define GROUP3_DATA_PIN 18
#define GROUP3_CLOCK_PIN 19
#define GROUP3_CHIP_SELECT_PIN 20

#define GROUP4_DATA_PIN 22
#define GROUP4_CLOCK_PIN 23
#define GROUP4_CHIP_SELECT_PIN 24

#define HALL_SENSOR_PIN 14
#define LED_RESET_PIN 8

#define SD_CARD_CS_PIN 9
#define SD_CARD_CLOCK_PIN 10
#define SD_CARD_MOSI_PIN 11
#define SD_CARD_MISO_PIN 12